name: Poll Status

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  poll:
    runs-on: ubuntu-latest
    steps:
      - name: Call backend
        run: |
          curl -X POST https://status-aggregator-backend.onrender.com/internal/poll-status \
          -H "X-Cron-Secret:cron-secret"
